version: '3.5'

x-rack: &rack
  image: 18xx_rack:dev
  environment:
    DATABASE_URL: postgres://root:password@db:5432/18xx_development
    RACK_ENV: development
    RUBYOPTS: --jit
  volumes:
    - .:/18xx
    - /18xx/vendor

services:
  rack:
    <<: *rack
    ports:
      - 9292:9292

  queue:
    <<: *rack
    command: bundle exec ruby queue.rb # bundle exec rerun --background -i 'build/*' -i 'public/*' 'ruby queue.rb'

  pg-exporter:
    environment:
      DATA_SOURCE_URI: db:5432/18xx_development?sslmode=disable
      DATA_SOURCE_USER: root
      DATA_SOURCE_PASS: password

  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 18xx_development

