version: '3.5'

services:
  rack:
    build: .
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: "10m"

  queue:
    build: .
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: "10m"

  redis:
    build: ./redis/
    logging:
      options:
        max-size: "10m"

  prometheus:
    build: ./prometheus/
    depends_on:
      - pg-exporter
    volumes:
      - ./prometheus/data:/prometheus
    ports:
      - 127.0.0.1:9090:9090
    logging:
      options:
        max-size: "10m"

  pg-exporter:
    build: ./pg-exporter/
    depends_on:
      - db
    ports:
      - 127.0.0.1:9187:9187
    logging:
      options:
        max-size: "10m"

  db:
    build: ./db/
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432
    logging:
      options:
        max-size: "10m"
